### PR TITLE
Added Page Change Handler and Carthage info to Readme.

### PR DESCRIPTION
**Pull request by JFKingsley**
Heya.

Last PR, I swear.. Just patched up the final thing I needed, and thought it might be useful as a general function.

Edit: Also added a quick function to easily change your page programatically.

If there are any issues, feel free to ping me!

### CODE REVIEW

**Comment by Esqarrouth** [comment]
It has a merge conflict at the moment. Can you fix it and resend the request? Thats the problem with big pull requests :(

I'll update the release version after your update

**Comment by JFKingsley** [comment]
All fixed! Just a little Readme issue, should be good to go now.

**Comment by Esqarrouth** [comment]
Good additions, did some extra stuff and made a new release version

https://github.com/goktugyil/EZSwipeController/commit/1d56247490382dbaa66f971516ba0f54a0e0257c
https://github.com/goktugyil/EZSwipeController/commit/9ef11b68e8925b0755dbf3d507ef39cde6e26d79

**Comment by JFKingsley** [comment]
Great, thanks!

**Pull request merged**
